const express=require("express");
const path=require("path");
const {Pool}=require("pg");
const app=express();app.use(express.json({limit:"1mb"}));
const PORT=process.env.PORT||10000, BUSINESS_NAME=process.env.BUSINESS_NAME||"IGOSA SERVICES", BUSINESS_PHONE=process.env.BUSINESS_PHONE||"+226 65 23 73 82";
if(!process.env.DATABASE_URL){console.error("DATABASE_URL manquante");process.exit(1)}
const pool=new Pool({connectionString:process.env.DATABASE_URL,ssl:process.env.NODE_ENV==="production"?{rejectUnauthorized:false}:false});
async function initDb(){
await pool.query(`CREATE TABLE IF NOT EXISTS products(id SERIAL PRIMARY KEY,name TEXT NOT NULL,category TEXT NOT NULL DEFAULT 'Divers',description TEXT NOT NULL DEFAULT '',price INTEGER NOT NULL DEFAULT 0,promo_price INTEGER,stock INTEGER NOT NULL DEFAULT 0,variants TEXT NOT NULL DEFAULT '',image_url TEXT NOT NULL DEFAULT '',status TEXT NOT NULL DEFAULT 'Actif',created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW());
CREATE TABLE IF NOT EXISTS orders(id SERIAL PRIMARY KEY,product_id INTEGER REFERENCES products(id) ON DELETE SET NULL,product_name TEXT NOT NULL DEFAULT '',variant TEXT NOT NULL DEFAULT '',quantity INTEGER NOT NULL DEFAULT 1,unit_price INTEGER NOT NULL DEFAULT 0,total_price INTEGER NOT NULL DEFAULT 0,customer_name TEXT NOT NULL DEFAULT '',customer_phone TEXT NOT NULL DEFAULT '',city TEXT NOT NULL DEFAULT '',address TEXT NOT NULL DEFAULT '',delivery TEXT NOT NULL DEFAULT '',comment TEXT NOT NULL DEFAULT '',status TEXT NOT NULL DEFAULT 'New',created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW());
CREATE TABLE IF NOT EXISTS conversations(id SERIAL PRIMARY KEY,customer_phone TEXT NOT NULL,customer_name TEXT NOT NULL DEFAULT '',last_message TEXT NOT NULL DEFAULT '',intent TEXT NOT NULL DEFAULT '',status TEXT NOT NULL DEFAULT 'Open',created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW())`);
const c=await pool.query("SELECT COUNT(*)::int n FROM products");if(c.rows[0].n===0)await pool.query(`INSERT INTO products(name,category,description,price,stock,variants) VALUES ('Portefeuille RFID','Portefeuilles','Portefeuille compact avec protection RFID.',5000,20,'Noir, Marron'),('Sac à main','Sacs','Sac à main pratique pour usage quotidien.',6000,15,'Noir, Marron'),('Montre classique','Montres','Montre classique élégante.',6000,10,'Noir, Argent')`);
}
const pp=b=>({name:String(b.name||"").trim(),category:String(b.category||"Divers").trim(),description:String(b.description||"").trim(),price:Math.round(Number(b.price||0)),promo_price:b.promo_price===""||b.promo_price==null?null:Math.round(Number(b.promo_price)),stock:Math.max(0,Math.round(Number(b.stock||0))),variants:String(b.variants||""),image_url:String(b.image_url||""),status:String(b.status||"Actif")});
app.get("/api/health",async(_q,r)=>{try{await pool.query("SELECT 1");r.json({ok:true,database:"connected"})}catch(e){r.status(500).json({ok:false,error:e.message})}});
app.get("/api/config",(_q,r)=>r.json({business_name:BUSINESS_NAME,business_phone:BUSINESS_PHONE}));
app.get("/api/dashboard",async(_q,r)=>{try{let [p,o,c]=await Promise.all([pool.query("SELECT COUNT(*)::int n FROM products"),pool.query("SELECT COUNT(*)::int n FROM orders"),pool.query("SELECT COUNT(*)::int n FROM conversations")]);r.json({products:p.rows[0].n,orders:o.rows[0].n,conversations:c.rows[0].n,business_name:BUSINESS_NAME})}catch(e){r.status(500).json({error:e.message})}});
app.get("/api/products",async(_q,r)=>{try{r.json((await pool.query("SELECT * FROM products ORDER BY id DESC")).rows)}catch(e){r.status(500).json({error:e.message})}});
app.post("/api/products",async(q,r)=>{try{let p=pp(q.body);if(!p.name)return r.status(400).json({error:"Nom obligatoire"});let x=await pool.query("INSERT INTO products(name,category,description,price,promo_price,stock,variants,image_url,status) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9) RETURNING *",[p.name,p.category,p.description,p.price,p.promo_price,p.stock,p.variants,p.image_url,p.status]);r.status(201).json(x.rows[0])}catch(e){r.status(500).json({error:e.message})}});
app.put("/api/products/:id",async(q,r)=>{try{let p=pp(q.body),x=await pool.query("UPDATE products SET name=$1,category=$2,description=$3,price=$4,promo_price=$5,stock=$6,variants=$7,image_url=$8,status=$9,updated_at=NOW() WHERE id=$10 RETURNING *",[p.name,p.category,p.description,p.price,p.promo_price,p.stock,p.variants,p.image_url,p.status,q.params.id]);if(!x.rows[0])return r.status(404).json({error:"Produit introuvable"});r.json(x.rows[0])}catch(e){r.status(500).json({error:e.message})}});
app.delete("/api/products/:id",async(q,r)=>{try{let x=await pool.query("DELETE FROM products WHERE id=$1",[q.params.id]);if(!x.rowCount)return r.status(404).json({error:"Produit introuvable"});r.json({ok:true})}catch(e){r.status(500).json({error:e.message})}});
app.get("/api/orders",async(_q,r)=>{try{r.json((await pool.query("SELECT * FROM orders ORDER BY id DESC")).rows)}catch(e){r.status(500).json({error:e.message})}});
app.post("/api/orders",async(q,r)=>{try{let b=q.body,qty=Math.max(1,Math.round(Number(b.quantity||1))),unit=Math.max(0,Math.round(Number(b.unit_price||0)));let x=await pool.query("INSERT INTO orders(product_id,product_name,variant,quantity,unit_price,total_price,customer_name,customer_phone,city,address,delivery,comment,status) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13) RETURNING *",[b.product_id||null,String(b.product_name||""),String(b.variant||""),qty,unit,qty*unit,String(b.customer_name||""),String(b.customer_phone||""),String(b.city||""),String(b.address||""),String(b.delivery||""),String(b.comment||""),String(b.status||"New")]);r.status(201).json(x.rows[0])}catch(e){r.status(500).json({error:e.message})}});
app.put("/api/orders/:id",async(q,r)=>{try{let x=await pool.query("UPDATE orders SET status=$1,updated_at=NOW() WHERE id=$2 RETURNING *",[String(q.body.status||"New"),q.params.id]);if(!x.rows[0])return r.status(404).json({error:"Commande introuvable"});r.json(x.rows[0])}catch(e){r.status(500).json({error:e.message})}});
app.get("/api/conversations",async(_q,r)=>{try{r.json((await pool.query("SELECT * FROM conversations ORDER BY updated_at DESC")).rows)}catch(e){r.status(500).json({error:e.message})}});
app.post("/api/conversations",async(q,r)=>{try{let b=q.body,x=await pool.query("INSERT INTO conversations(customer_phone,customer_name,last_message,intent,status) VALUES($1,$2,$3,$4,$5) RETURNING *",[String(b.customer_phone||""),String(b.customer_name||""),String(b.last_message||""),String(b.intent||""),String(b.status||"Open")]);r.status(201).json(x.rows[0])}catch(e){r.status(500).json({error:e.message})}});
app.get("/webhook/whatsapp",(q,r)=>{if(q.query["hub.mode"]==="subscribe"&&q.query["hub.verify_token"]===process.env.WHATSAPP_VERIFY_TOKEN)return r.status(200).send(q.query["hub.challenge"]);r.sendStatus(403)});
app.post("/webhook/whatsapp",(q,r)=>{console.log("WhatsApp webhook:",JSON.stringify(q.body));r.sendStatus(200)});
app.use(express.static(path.join(__dirname,"public")));app.get("*",(_q,r)=>r.sendFile(path.join(__dirname,"public","index.html")));
initDb().then(()=>app.listen(PORT,()=>console.log(BUSINESS_NAME+" running on "+PORT))).catch(e=>{console.error(e);process.exit(1)});